version: '3.8'

services:
  discord-bot:
  container_name: discord-music-bot
  environment:
     - DISCORD_TOKEN=${DISCORD_TOKEN}
  restart: unless-stopped
  volumes:
     - ./DiscordMusicBot.py:/app/DiscordMusicBot.py